version: '3.9'
services:
    web_proxy1:
        image: nginx
        ports:
            - 80:80
        networks:
            app_net:
                ipv4_address: 172.16.0.10
        COPY ./nginx.conf /etc/nginx/nginx.conf
networks:
    app_net:
        ipam:
            driver: default
            config:
                - subnet: "172.16.0.0/24"
